version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile # Path to your Dockerfile
    ports:
      - "8000:8000" # Map host's (your system) port 8000 to container port 8000
    depends_on:
      - redis
      - memcached
      - celery
    environment:
      REDIS_URL: "redis://redis-server:6379/0"
      MEMCACHE_HOST: "memcache-server"
      MEMCACHE_PORT: 11211
      CELERY_BROKER_URL: "redis://redis-server:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis-server:6379/0"
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - backend

  memcached:
    image: memcached:alpine
    container_name: memcache-server
    ports:
      - "11211:11211"
    networks:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    depends_on:
      - redis
      - memcached
    environment:
      MEMCACHE_HOST: "memcache-server"
      MEMCACHE_PORT: 11211
      CELERY_BROKER_URL: "redis://redis-server:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis-server:6379/0"
    command: celery -A worker.celery_worker.celery_app worker --loglevel=info --pool=solo
    networks:
      - backend

networks:
  backend:
    driver: bridge # Use the default network driver for the backend network
